import { MenuItem } from './types';

export const menuItems: MenuItem[] = [
    // ─── FOOD ────────────────────────────────────────────────────────────────────
    {
        id: 'food-001',
        name: 'Nasi Goreng Spesial',
        description: 'Fragrant fried rice with egg, chicken, vegetables & prawn crackers',
        price: 45000,
        category: 'Food',
        emoji: '🍳',
        color: 'from-amber-400 to-orange-500',
        popular: true,
    },
    {
        id: 'food-002',
        name: 'Ayam Bakar',
        description: 'Charcoal-grilled marinated chicken with sambal & steamed rice',
        price: 55000,
        category: 'Food',
        emoji: '🍗',
        color: 'from-orange-400 to-red-500',
        popular: true,
    },
    {
        id: 'food-003',
        name: 'Mie Goreng',
        description: 'Stir-fried egg noodles with vegetables, egg & sweet soy sauce',
        price: 38000,
        category: 'Food',
        emoji: '🍜',
        color: 'from-yellow-400 to-amber-500',
    },
    {
        id: 'food-004',
        name: 'Soto Betawi',
        description: 'Rich coconut milk beef soup with tomato, potatoes & emping',
        price: 50000,
        category: 'Food',
        emoji: '🍲',
        color: 'from-amber-300 to-yellow-500',
    },
    {
        id: 'food-005',
        name: 'Gado-Gado',
        description: 'Fresh vegetables with tofu, tempeh & creamy peanut sauce',
        price: 35000,
        category: 'Food',
        emoji: '🥗',
        color: 'from-green-400 to-emerald-500',
    },
    {
        id: 'food-006',
        name: 'Rendang Daging',
        description: 'Slow-cooked beef in rich spiced coconut milk, served with rice',
        price: 75000,
        category: 'Food',
        emoji: '🥩',
        color: 'from-red-400 to-rose-600',
        popular: true,
    },
    {
        id: 'food-007',
        name: 'Bakso Spesial',
        description: 'Meatball soup with noodles, tofu & homemade beef broth',
        price: 32000,
        category: 'Food',
        emoji: '🍡',
        color: 'from-rose-300 to-pink-500',
    },
    {
        id: 'food-008',
        name: 'Ikan Bakar',
        description: 'Grilled fish with bumbu rujak sauce, lalapan & sambal',
        price: 65000,
        category: 'Food',
        emoji: '🐟',
        color: 'from-blue-300 to-cyan-500',
    },

    // ─── DRINKS ──────────────────────────────────────────────────────────────────
    {
        id: 'drink-001',
        name: 'Es Teh Manis',
        description: 'Classic sweet iced tea, perfectly refreshing',
        price: 8000,
        category: 'Drinks',
        emoji: '🧋',
        color: 'from-amber-200 to-yellow-400',
        popular: true,
    },
    {
        id: 'drink-002',
        name: 'Jus Alpukat',
        description: 'Creamy blended avocado with condensed milk & chocolate drizzle',
        price: 22000,
        category: 'Drinks',
        emoji: '🥑',
        color: 'from-green-300 to-lime-500',
    },
    {
        id: 'drink-003',
        name: 'Kopi Susu Kekinian',
        description: 'Espresso with fresh milk, lightly sweetened with palm sugar',
        price: 28000,
        category: 'Drinks',
        emoji: '☕',
        color: 'from-stone-400 to-amber-700',
        popular: true,
    },
    {
        id: 'drink-004',
        name: 'Es Kelapa Muda',
        description: 'Fresh young coconut water with coconut flesh',
        price: 18000,
        category: 'Drinks',
        emoji: '🥥',
        color: 'from-teal-300 to-cyan-400',
    },
    {
        id: 'drink-005',
        name: 'Jus Jeruk Segar',
        description: 'Freshly squeezed orange juice, served chilled',
        price: 15000,
        category: 'Drinks',
        emoji: '🍊',
        color: 'from-orange-300 to-amber-400',
    },
    {
        id: 'drink-006',
        name: 'Cincau Hijau',
        description: 'Green grass jelly drink with coconut milk & palm sugar',
        price: 12000,
        category: 'Drinks',
        emoji: '🌿',
        color: 'from-emerald-300 to-green-500',
    },

    // ─── DESSERTS ────────────────────────────────────────────────────────────────
    {
        id: 'dessert-001',
        name: 'Es Campur',
        description: 'Mixed shaved ice with fruits, jelly, sweet potato & coconut milk',
        price: 20000,
        category: 'Desserts',
        emoji: '🍧',
        color: 'from-pink-300 to-rose-400',
        popular: true,
    },
    {
        id: 'dessert-002',
        name: 'Pisang Goreng',
        description: 'Crispy fried banana fritters with melted cheese & condensed milk',
        price: 18000,
        category: 'Desserts',
        emoji: '🍌',
        color: 'from-yellow-300 to-amber-400',
    },
    {
        id: 'dessert-003',
        name: 'Puding Coklat',
        description: 'Rich chocolate pudding with vanilla sauce & chocolate shavings',
        price: 15000,
        category: 'Desserts',
        emoji: '🍮',
        color: 'from-amber-600 to-stone-700',
    },
    {
        id: 'dessert-004',
        name: 'Kolak Pisang',
        description: 'Banana in sweet coconut milk with palm sugar & pandan leaf',
        price: 16000,
        category: 'Desserts',
        emoji: '🍵',
        color: 'from-yellow-200 to-amber-300',
    },
    {
        id: 'dessert-005',
        name: 'Klepon',
        description: 'Pandan rice balls filled with palm sugar, coated with coconut',
        price: 12000,
        category: 'Desserts',
        emoji: '🟢',
        color: 'from-green-200 to-emerald-400',
    },
    {
        id: 'dessert-006',
        name: 'Cendol',
        description: 'Pandan jelly with coconut milk, shaved ice & palm sugar syrup',
        price: 14000,
        category: 'Desserts',
        emoji: '🍨',
        color: 'from-lime-300 to-green-500',
        popular: true,
    },
];
